// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhedwiumrbiowwtkebym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZWR3aXVtcmJpb3d3dGtlYnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODM5NzQsImV4cCI6MjA1NjE1OTk3NH0.6XIE_sLyeaMSKmFfs8s49BxaXpLTgQNJwTrBHyNkblg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);